<a href="https://colab.research.google.com/github/pankajmahtolia/Machine-Learning/blob/Regression/Multi_LR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset= pd.read_csv('50_Startups.csv')
X= dataset.iloc[:, :-1].values
y= dataset.iloc[:, -1].values

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X= np.array(ct.fit_transform(X))


In [ ]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=1)

**Training the Multiple Linear Regression model on the Training set**

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

**Predicting the Test set results**

In [ ]:
y_pred= lr.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate(  (y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)), axis=1 ))

[[114664.42 105008.31]
 [ 90593.16  96479.51]
 [ 75692.84  78239.91]
 [ 70221.89  81229.06]
 [179790.26 191050.39]
 [171576.92 182901.99]
 [ 49753.59  35673.41]
 [102276.66 101004.64]
 [ 58649.38  49490.75]
 [ 98272.03  97483.56]]


**Predicting the Train set results**

In [ ]:
X_pred= lr.predict(X_train)
np.set_printoptions(precision=2)
print(np.concatenate(  (X_pred.reshape(len(X_pred), 1), y_train.reshape(len(y_train),1)), axis=1 ))

[[ 98762.25  97427.84]
 [ 83684.21  81005.76]
 [117738.47 111313.02]
 [ 76944.37  90708.19]
 [115291.17 122776.86]
 [ 71227.43  71498.49]
 [ 49751.28  14681.4 ]
 [110978.09 105733.54]
 [115041.51 110352.25]
 [126810.36 134307.35]
 [ 75687.34  77798.83]
 [129921.03 125370.37]
 [ 49479.62  64926.08]
 [112608.52 108552.04]
 [110240.44 108733.99]
 [169898.04 166187.94]
 [ 98337.38  96778.92]
 [148949.08 132602.65]
 [ 99680.66  99937.59]
 [134630.56 146121.95]
 [102970.71 103282.38]
 [ 66080.31  65200.33]
 [ 90106.07  96712.8 ]
 [128628.02 124266.9 ]
 [116157.82 118474.03]
 [102294.06 107404.34]
 [156091.38 156122.51]
 [159019.4  155752.6 ]
 [ 48270.78  42559.73]
 [186863.18 191792.06]
 [116454.65 126992.93]
 [190209.72 192261.83]
 [144915.12 129917.04]
 [161491.05 156991.12]
 [133859.59 144259.4 ]
 [152846.32 149759.96]
 [150770.52 152211.77]
 [128837.66 141585.52]
 [ 61653.87  69758.98]
 [ 88888.38  89949.14]]


In [ ]:
#Making a single prediction (for example the profit of a startup with R&D Spend = 160000, Administration Spend = 130000, Marketing Spend = 300000 and State = 'California')
print(lr.predict([[1, 0, 0, 160000, 130000, 300000]]))

[180892.25]
